@echo off
echo Initializing git repository...
git init
echo Adding files...
git add README.md
echo Creating commit...
git commit -m "first commit"
echo Renaming branch to main...
git branch -M main
echo Adding remote origin...
git remote add origin https://github.com/theaniketpawar1/Paradox.git
echo Pushing to GitHub...
git push -u origin main
echo.
echo Done! Repository: https://github.com/theaniketpawar1/Paradox
